### ISSUE TITLE
Serialization of Tags is not working correctly

### ISSUE THREAD

**Issue by MaggieKimani1** [microsoft/OpenAPI.NET#1922]
**Describe the bug**
In V2.0, tags aren't properly serialized which leads to loss of information

**OpenApi File To Reproduce**
A document with tags at the root level defined as below:
```yaml
tags:
  - name: City.City
    x-ms-docs-toc-type: page
  - name: CountryOrRegion.CountryOrRegion
    x-ms-docs-toc-type: page
  - name: Me.Person
    x-ms-docs-toc-type: page
  - name: People.Person
    x-ms-docs-toc-type: page
```
Emits:
```yaml
tags:
  - City.City
  - CountryOrRegion.CountryOrRegion
  - Me.Person
  - People.Person
```

**Expected behavior**
All properties for root-level tags should be written out properly
