### ISSUE TITLE
openapi, Security parse issue: openApiSecurityScheme.Flows will always be null.

### ISSUE THREAD

**Issue by partychen** [Microsoft/OpenAPI.NET#222]
for example, parse below content of security,  the flows will be always empty. And in the v1.0.0-beta012 it works, but in v1.0.0-beta014 it was broken.

```yaml
components:
  securitySchemes:
    azure_auth: 
      type: oauth2
      description: Azure Active Directory OAuth2 Flow.
      in: header
      flows: 
        implicit:
          authorizationUrl: https://example.com/api/oauth/dialog
          tokenUrl: https://example.com/token
          scopes:
            user_impersonation: modify pets in your account
            read: read your pets
        authorizationCode:
          authorizationUrl: https://example.com/api/oauth/dialogcode
          tokenUrl: https://example.com/api/oauth/tokencode
          scopes:
            user_impersonation: modify pets in your account code.
            read: read your pets code.
```
