### ISSUE TITLE
Parsing OpenAPI V2 external references creates broken reference

### ISSUE THREAD

**Issue by darrelmiller** [microsoft/OpenAPI.NET#804]
See this example from Keyvault https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2021-10-01/keyvault.json

```yaml
       default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: common.json#/components/schemas/definitions/CloudError
```
