### ISSUE TITLE
Append `Format` property value to root schema when serializing as v2 if contained in `anyOf`, `allOf`, `oneOf` of child schemas

### ISSUE THREAD

**Issue by irvinesunday** [microsoft/OpenAPI.NET#992]
When a primitive type schema of the example:

```
var schema = new OpenApiSchema();
if (context.Settings.IEEE754Compatible)
{
    schema.OneOf = new List<OpenApiSchema>
    {
        new OpenApiSchema { Type = "number", Format = "decimal" },
        new OpenApiSchema { Type = "string" },
    };
}
```
The **expected** serialization for **v2** should look like below:

```
Age:
  format: int64
```
and the **expected** serialization for **v3**:

```
Age:
  oneOf:
    - type: integer
       format: int64
    - type: string
  nullable: true
```

This should be applicable to all primitive type schemas.
